-- MySQL Script generated by MySQL Workbench
-- Sat Feb  6 23:14:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mercadofacil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadofacil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadofacil` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mercadofacil` ;

-- -----------------------------------------------------
-- Table `mercadofacil`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `logradouro` VARCHAR(45) NOT NULL COMMENT '',
  `numero` INT(11) NOT NULL COMMENT '',
  `bairro` VARCHAR(45) NOT NULL COMMENT '',
  `complemento` VARCHAR(45) NOT NULL COMMENT '',
  `cep` VARCHAR(45) NOT NULL COMMENT '',
  `cidade` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`consumidor` (
  `cpf` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `tipoPerfil` VARCHAR(45) NOT NULL COMMENT '',
  `idEndereco` INT(11) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`cpf`, `email`)  COMMENT '',
  INDEX `fkConsumidorEndereco_idx` (`idEndereco` ASC)  COMMENT '',
  CONSTRAINT `fkConsumidorEndereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mercadofacil`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`supermercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`supermercado` (
  `nomeFantasia` VARCHAR(45) NOT NULL COMMENT '',
  `razaoSocial` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`nomeFantasia`, `razaoSocial`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`comerciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`comerciante` (
  `cnpj` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `tipoPerfil` VARCHAR(45) NOT NULL COMMENT '',
  `idEndereco` INT(11) NOT NULL COMMENT '',
  `nfEmpresa` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `rsEmpresa` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`cnpj`, `email`)  COMMENT '',
  INDEX `fkComercianteEndereco_idx` (`idEndereco` ASC)  COMMENT '',
  INDEX `fkComercianteSupermercado_idx` (`nfEmpresa` ASC, `rsEmpresa` ASC)  COMMENT '',
  CONSTRAINT `fkComercianteEndereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mercadofacil`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkComercianteSupermercado`
    FOREIGN KEY (`nfEmpresa` , `rsEmpresa`)
    REFERENCES `mercadofacil`.`supermercado` (`nomeFantasia` , `razaoSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`anunciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`anunciante` (
  `cnpj` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `razaoSocial` VARCHAR(45) NOT NULL COMMENT '',
  `causa` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `tipoPerfil` VARCHAR(45) NOT NULL COMMENT '',
  `idEndereco` INT(11) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`cnpj`, `email`, `razaoSocial`)  COMMENT '',
  INDEX `fkAnuncianteEndereco_idx` (`idEndereco` ASC)  COMMENT '',
  CONSTRAINT `fkAnuncianteEndereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mercadofacil`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`servicos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `descricao` VARCHAR(240) NOT NULL COMMENT '',
  `cnpj` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `anuncianteRazao` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ServicosAnunciante_idx` (`cnpj` ASC, `email` ASC, `anuncianteRazao` ASC)  COMMENT '',
  CONSTRAINT `ServicosAnunciante`
    FOREIGN KEY (`cnpj` , `email` , `anuncianteRazao`)
    REFERENCES `mercadofacil`.`anunciante` (`cnpj` , `email` , `razaoSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `categoria` VARCHAR(45) NOT NULL COMMENT '',
  `descricao` VARCHAR(240) NOT NULL COMMENT '',
  `cnpjAnunciante` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `emailAnunciante` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `razaoSocialAnunciante` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nomeFantasiaSupermercado` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `razaoSocialSupermercado` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `empresaAnunc_idx` (`cnpjAnunciante` ASC, `emailAnunciante` ASC, `razaoSocialAnunciante` ASC)  COMMENT '',
  INDEX `empresaSuper_idx` (`nomeFantasiaSupermercado` ASC, `razaoSocialSupermercado` ASC)  COMMENT '',
  CONSTRAINT `empresaAnunc`
    FOREIGN KEY (`cnpjAnunciante` , `emailAnunciante` , `razaoSocialAnunciante`)
    REFERENCES `mercadofacil`.`anunciante` (`cnpj` , `email` , `razaoSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empresaSuper`
    FOREIGN KEY (`nomeFantasiaSupermercado` , `razaoSocialSupermercado`)
    REFERENCES `mercadofacil`.`supermercado` (`nomeFantasia` , `razaoSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mercadofacil`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofacil`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `statusEntrega` VARCHAR(45) NOT NULL COMMENT '',
  `valorTotal` DOUBLE NOT NULL COMMENT '',
  `cpfConsumidor` VARCHAR(14) NOT NULL COMMENT '',
  `emailConsumidor` VARCHAR(45) NOT NULL COMMENT '',
  `descricaoProdutos` TEXT(10000) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fkCompraConsumidor_idx` (`cpfConsumidor` ASC, `emailConsumidor` ASC)  COMMENT '',
  CONSTRAINT `fkCompraConsumidor`
    FOREIGN KEY (`cpfConsumidor` , `emailConsumidor`)
    REFERENCES `mercadofacil`.`consumidor` (`cpf` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
